export const groceries = [
    { id: 1, name: "Cauliflower", price: "₹98.40", image: "https://images.pexels.com/photos/7572005/pexels-photo-7572005.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Fruits and Vegetables" },
    { id: 2, name: "Brinjal", price: "₹65.60", image: "https://media.istockphoto.com/id/1438550144/photo/full-frame-image-of-pile-of-aubergines-in-crate-on-supermarket-shelves-elevated-view.jpg?b=1&s=612x612&w=0&k=20&c=e3KhnJX2YOVHP9H9OoXEc4sdjxrDfUiaOucqUyPytPc=", category: "Fruits and Vegetables" },
    { id: 3, name: "Garlic", price: "₹82.00", image: "https://images.pexels.com/photos/1392585/pexels-photo-1392585.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Fruits and Vegetables" },
    { id: 4, name: "Tomato", price: "₹73.80", image: "https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg", category: "Fruits and Vegetables" },
    { id: 5, name: "Onion", price: "₹57.40", image: "https://images.pexels.com/photos/7129153/pexels-photo-7129153.jpeg", category: "Fruits and Vegetables" },
    { id: 6, name: "Carrot", price: "₹61.50", image: "https://images.pexels.com/photos/143133/pexels-photo-143133.jpeg", category: "Fruits and Vegetables" },
    { id: 7, name: "Potato", price: "₹49.20", image: "https://images.pexels.com/photos/2286776/pexels-photo-2286776.jpeg", category: "Fruits and Vegetables" },
    { id: 8, name: "Cucumber", price: "₹69.70", image: "https://images.pexels.com/photos/2329440/pexels-photo-2329440.jpeg", category: "Fruits and Vegetables" },
    { id: 9, name: "Spinach", price: "₹90.20", image: "https://images.pexels.com/photos/6824475/pexels-photo-6824475.jpeg", category: "Fruits and Vegetables" },
    { id: 10, name: "Raddish", price: "₹164.00", image: "https://media.istockphoto.com/id/945482424/photo/vegetables.jpg?b=1&s=612x612&w=0&k=20&c=g9L4TBBwl6x5g4Y7YHEhjEZ-YT9z7Tf_cV7PmiH1mLA=", category: "Fruits and Vegetables" },
    { id: 11, name: "Wheat & Flour", price: "₹287.00", image: "https://odhi.in/image/cache/catalog/grocery/flour-rava/aashirvaad-atta-whole-wheat-1-kg-front-sale-online-coimbatore-1000x1000.jpg", category: "Daily Staples" },
    { id: 12, name: "Spices", price: "₹180.40", image: "https://asset20.ckassets.com/blog/wp-content/uploads/sites/5/2022/08/Tata-Sampann-Masala-1024x512.jpg", category: "Daily Staples" },
    { id: 13, name: "Chickpeas", price: "₹410.00", image: "https://ishva.co.in/wp-content/uploads/2023/09/Chik-peas_500-mg-1.jpg", category: "Daily Staples" },
    { id: 14, name: "Refined Sugar", price: "₹147.60", image: "https://madhursugar.com/assets/images/madhur-sugar-green-pack.png", category: "Daily Staples" },
    { id: 15, name: "Nescafe coffee", price: "₹123.00", image: "https://asset20.ckassets.com/blog/wp-content/uploads/sites/5/2021/10/Nescafe.jpg", category: "Daily Staples" },
    { id: 16, name: "Cooking oil", price: "₹205.00", image: "https://images.jdmagicbox.com/rep/b2b/fortune-cooking-oil/fortune-cooking-oil-6.jpg", category: "Daily Staples" },
    { id: 17, name: "Dals and pulses", price: "₹123.00", image: "https://indiaphile.info/wp-content/uploads/2022/09/stp-lentils-1773-1240x649.jpg", category: "Daily Staples" },
    { id: 18, name: "Butter", price: "₹3.00", image: "https://asset20.ckassets.com/blog/wp-content/uploads/sites/5/2022/01/3-4-1024x512.jpg", category: "Daily Staples" },  
    { id: 19, name: "Salts", price: "₹6.00", image: "https://asset20.ckassets.com/blog/wp-content/uploads/sites/5/2022/09/Tata-1024x512.jpg", category: "Daily Staples" },  
    { id: 20, name: "Tomato Ketchup", price: "₹8.00", image: "https://images.pexels.com/photos/8455314/pexels-photo-8455314.jpeg?auto=compress&cs=tinysrgb&w=600", category: "Daily Staples" },
    { id: 21, name: "Disinfectant cleaner", price: "₹250.00", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCi_Ndb0qm6-AWML-CAiUmecMgqMmrzfpewQ&s", category: "Cleaning Household" },
    { id: 22, name: "Dishwashing Liquid", price: "₹180.00", image: "https://www.dayjoy.in/ProductImages/Dishwash.jpg", category: "Cleaning Household" },
    { id: 23, name: "Floor Cleaner", price: "₹320.00", image: "https://relianceretail.com/img/brands/consumer-brands/home-and-personal-hygiene/my-home/my-home-floor-cleaner/aqua-1l.jpg", category: "Cleaning Household" },
    { id: 24, name: "Harpic", price: "₹210.00", image: "https://rukminim2.flixcart.com/image/850/1000/xif0q/toilet-cleaner/m/k/b/-original-imagymncmshw7ds8.jpeg?q=90&crop=false", category: "Cleaning Household" },
    { id: 25, name: "Freshners", price: "₹150.00", image: "https://m.media-amazon.com/images/I/71EX5zkUwaL.jpg", category: "Cleaning Household" },
  ];